### ISSUE TITLE
Wezterm types

### ISSUE THREAD

**Issue by Uzaaft** [MariaSolOs/dotfiles#1]
Folke uses lazy.nvim to handle/manage/keep track of a repository that has type info(type stubs...?)
You can find it here: https://github.com/justinsgithub/wezterm-types
I have the following in my neovim conf: 
```lua
...other plugin tables
  { "justinsgithub/wezterm-types" }
...other plugin tables
```

I then added a `.neoconf.json` file in the wezterm folder:
```
{
  "lspconfig": {
    "lua_ls": {
      "Lua.workspace.library": [
        "/Users/uzaaft/.local/share/nvim/lazy/wezterm-types/types"
      ]
    }
  }
}
```

And then at the top of `wezterm.lua`:
```lua
---@type Wezterm
```

**Comment by Uzaaft** [comment]
By the way @MariaSolOs Huge fan of the dots, I steal...I mean lend stuff from it all the time 🙊

**Comment by MariaSolOs** [comment]
@Uzaaft Oh nice! Thanks :)
And lol my dotfiles are one of the few things I'm actually fine with people stealing ;)
