### ISSUE TITLE
Question: Fedora

### ISSUE THREAD

**Issue by Uzaaft** [MariaSolOs/dotfiles#3]
Good day @MariaSolOs ,

Love the stuff you have here, I take a look weekly to see if you've done something I should add to my config.

A quick Q about your current setup: Are you by any chance running fedora on your mac? I saw the new default branch, and began to wonder.

**Comment by MariaSolOs** [comment]
Hey @Uzaaft! Glad you find my dotfiling helpful :)

> Are you by any chance running fedora on your mac? I saw the new default branch, and began to wonder.

I am. I started using [Asahi](https://asahilinux.org/fedora/) on my MB M1. I installed the Fedora minimal image and migrated my setup from Arch.

**Comment by Uzaaft** [comment]
How did you find the experience of using asahi on the MB? Any hickups?

**Comment by MariaSolOs** [comment]
It's been great so far! Although I do miss Arch, using Fedora has been very straightforward.

**Comment by Uzaaft** [comment]
That's it, I'm installing it now 🤣
